# HomeLab Installer config

SERVER_USER=""
MEDIA_GROUP="media"
MEDIA_ROOT="/srv/media"
BACKUP_ROOT="/srv/backups"
CONFIG_ROOT="/srv/config"
RESTORE_ROOT="/srv/restore"

# Compartidos SMB por defecto
SMB_FOLDERS="peliculas series musica libros fotos videos downloads backups"

# Interfaz de red. Vacío = autodetectar
NETWORK_IFACE=""
